name: ci
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  merge_group:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: |
          chmod +x ./gradlew
          ./gradlew build
