name: ci
on:
  push:
    branches: '*'
  pull_request:
    branches: "*"
  merge_group:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Upload test report directory
        uses: actions/upload-artifact@v2
        with:
          name: testDebugStuff
          path: app/build/reports/tests/testDebugUnitTest/
          if-no-files-found: warn



      - name: Detekt
        run: |
          pwd
          ls -la
          ls -la ./config
          ls -la ./config/detekt/
          ./gradlew detekt

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
